server:
  port: ${CUSTOM.SERVER.PORT:8081}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

spring:
  cloud:
    gateway:
      routes:
      - id: msvc-licencias
        uri: lb://msvc-licencias
        predicates:
          - Path=/api/msvc-licencias/**
        filters:
          - StripPrefix=2

      - id: msvc-solicitantes
        uri: lb://msvc-solicitantes
        predicates:
          - Path=/api/msvc-solicitantes/**
        filters:
          - StripPrefix=2

      - id: msvc-usuarios
        uri: lb://msvc-usuarios
        predicates:
          - Path= /api/msvc-usuarios/**
        filters:
          - StripPrefix=2

jwt:
  security:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351