server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: msvc-licencias
        uri: lb://msvc-licencias
        predicates:
          - Path=/api/v1/licencias/**
        filters:
          - StripPrefix=2
      - id: msvc-solicitantes
        uri: lb://msvc-solicitantes
        predicates:
          - Path=/api/v1/solicitantes/**
        filters:
          - StripPrefix=2